version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: prefect_user
      POSTGRES_PASSWORD: prefect_pass
      POSTGRES_DB: prefect_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
