apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: monitoring
      sslmode: 'disable' 
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false